---
- name: Edge Configuration
  hosts: localhost
  gather_facts: no    
  tasks:
      
#---------------------------------------server configuration----------------------------------------------------------------------------------------------

    - name: Start nginx 
      shell: microk8s kubectl exec -it proxy -- nginx
