--
- name: Topology Deployment using kne
  hosts: localhost
  gather_facts: no
  tasks: 
 #--------------------------------------------Deploy kne---------------------------------------------------------------------------
 # Configure the path where the kne topology file 
    - name: Deploy vxlan-1
      shell: kubectl apply -f ~/L2S-M/edge/vxlan-1.yaml

   - name: Deploy network multus
      shell: kubectl create -f ~/L2S-M/edge/v-network-1.yaml 
      shell: kubectl create -f ~/L2S-M/edge/v-network-2.yaml 

    - name: deploy ned
      shell: kubectl apply -f ~/L2S-M/edge/ned.yaml

    - name: Deploy proxy
      shell: kkubectl apply -f ~/L2S-M/edge/proxy.yaml

    - name: Deploy client
      shell: kkubectl apply -f ~/L2S-M/edge/clients.yaml

    - name: Wait for 20 seconds
      pause:
        seconds: 20