---
- name: Deployment using L2S-M
  hosts: localhost
  gather_facts: no
  tasks:
    # --------------------------------------------Deploy kne--------------------------------------------
    # Configure the path where the kne topology file is deployed

    - name: undeploy vxlan-1
      shell: microk8s kubectl delete -f ~/NDT-Prototype/Topology/Edge/vxlan-1.yaml

    - name: undeploy network multus 
      shell: |
        microk8s kubectl delete -f ~/NDT-Prototype/Topology/Edge/v-network-1.yaml
        microk8s kubectl delete -f ~/NDT-Prototype/Topology/Edge/v-network-2.yaml

    - name: undeploy ned
      shell: microk8s kubectl delete -f ~/NDT-Prototype/Topology/Edge/ned.yaml

    - name: undeploy proxy
      shell: microk8s kubectl delete -f ~/NDT-Prototype/Topology/Edge/proxy.yaml

    - name: undeploy client
      shell: microk8s kubectl delete -f ~/NDT-Prototype/Topology/Edge/client.yaml

    - name: Wait for 20 seconds
      pause:
        seconds: 20
