version: '3.9'
services:
  client:
    build:
      context: ./client
      dockerfile: dockerfile
    ports:
      - "2222:22" #ssh
    image: client:last

  server:
    build:
      context: ./server
      dockerfile: dockerfile
    ports:
      - "2224:22" #ssh
    image: server:last


  proxy:
    build:
      context: ./proxy
      dockerfile: dockerfile
    ports:
      - "2226:22" #ssh
    image: proxy:last





  

  