---
- name: Topology Deployment using kne
  hosts: localhost
  gather_facts: no
  tasks: 
 #--------------------------------------------Deploy kne---------------------------------------------------------------------------
    - name: Deploy topology
      shell: kne create ~/NDT-Prototype/Topology/Network/Topology.yaml  # Configure the path where the kne topology file is

    - name: config map
      shell: #

    - name: Deploy gateway2
      shell: kubectl apply -f ~/NDT-Prototype/Topology/Network/gateway2.yaml

    - name: Wait for 20 seconds
      pause:
        seconds: 20
