apiVersion: v1
kind: Pod
metadata:
  name: client
  labels:
    app: test4
  annotations:
    k8s.v1.cni.cncf.io/networks: v-network-2
spec:
  containers:
  - name: client
    command: ["/bin/ash", "-c", "ip a add 10.0.2.2/24 dev net1 && trap : TERM INT; sleep infinity & wait"]
    image: alpine:latest
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
  #nodeName: test-l2sm-uc3m-polito-1
